// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMq7v35JNpfsLbm84DSmCwiABuSqqZPYo',
    appId: '1:190818478007:web:a4afc7b5fab8f53e162a32',
    messagingSenderId: '190818478007',
    projectId: 'tlu-blogger',
    authDomain: 'tlu-blogger.firebaseapp.com',
    storageBucket: 'tlu-blogger.firebasestorage.app',
    measurementId: 'G-9QC11FXWQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWBZtjXopEv-PeiOluUO4Zj1fq16OWOk',
    appId: '1:190818478007:android:123a170eb8e3732b162a32',
    messagingSenderId: '190818478007',
    projectId: 'tlu-blogger',
    storageBucket: 'tlu-blogger.firebasestorage.app',
  );
}
