name: schoolyard_heatmap
description: Ứng dụng khảo sát và trực quan hóa dữ liệu môi trường trong sân trường.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^5.0.0
  location: ^5.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
