name: lab1_2_2
description: A new Flutter project showing custom RichText usage.

# Cấu hình môi trường Dart/Flutter
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8   # icon iOS cơ bản
  url_launcher: ^6.1.10     # mở tel, mailto, http...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Nếu bạn muốn dùng thêm hình ảnh, khai báo ở đây
  assets:
    - assets/images/
